# -*- coding: utf-8 -*-
"""SMS SPAM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FN-wO_Y24mV5BO7O-VIgDv4tvcJmq_tg

1. Introduction

SMS is a common method of communication, but users often receive unwanted spam messages such as advertisements, fake offers and promotional messages. Identifying spam manually can be difficult. This project develops an NLP-based SMS Spam Detection system that automatically classifies messages as Ham or Spam.

The project uses text preprocessing, TF-IDF feature extraction, and a Multinomial Naive Bayes classifier. The model is evaluated using Accuracy, Precision, Recall, F1-score and a Confusion Matrix.

2. Project Description

The project follows these steps:

Dataset → Data Cleaning → Text Preprocessing → TF-IDF → Naive Bayes → Prediction → Evaluation

The SMS dataset contains two classes: Ham and Spam. Text preprocessing includes lowercase conversion, URL removal, special-character and number removal, stopword removal and stemming.

TF-IDF converts the cleaned SMS text into numerical features. These features are used to train the Multinomial Naive Bayes model. The system can also classify new SMS messages entered by the user.

1. IMPORT LIBRARIES
"""

import pandas as pd
import numpy as np
import re
import nltk
import matplotlib.pyplot as plt
import seaborn as sns

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)


# Download stopwords
nltk.download('stopwords')

""" 2. LOAD DATASET

"""

print("\nLoading dataset...")

df = pd.read_csv(
    "spam.csv",
    encoding="latin-1"
)

print("\nDataset loaded successfully!")

print("Original dataset shape:", df.shape)

"""3. DATASET INFORMATION"""

print("\nFirst five records:")
print(df.head())


print("\nOriginal columns:")
print(df.columns)


print("\nDataset shape:")
print(df.shape)

""" 4. SELECT REQUIRED COLUMNS"""

df = df[['v1', 'v2']]

# Rename columns for better understanding

df.columns = ['label', 'message']


print("\nAfter selecting required columns:")
print(df.head())

"""5. CHECK MISSING VALUES"""

print(df.isnull().sum())


# Remove missing values

df = df.dropna()


print("\nDataset shape after removing missing values:")
print(df.shape)

"""6. CHECK DUPLICATE VALUES"""

print("Number of duplicate messages:",
      df.duplicated().sum())


# Remove duplicate records

df = df.drop_duplicates()


print("Dataset shape after removing duplicates:")
print(df.shape)

"""7. CLASS DISTRIBUTION"""

print(df['label'].value_counts())


# Plot class distribution

plt.figure(figsize=(7, 5))

sns.countplot(
    data=df,
    x='label'
)

plt.title("Distribution of SMS Messages")

plt.xlabel("Message Category")

plt.ylabel("Number of Messages")

plt.show()

""" 8. TEXT PREPROCESSING"""

# Load English stopwords

stop_words = set(
    stopwords.words('english')
)


# Create stemmer

stemmer = PorterStemmer()


def preprocess_text(text):
    """
    Performs basic NLP text preprocessing.

    Steps:
    1. Convert text to lowercase
    2. Remove URLs
    3. Remove special characters
    4. Remove numbers
    5. Remove stopwords
    6. Perform stemming
    """

    # Convert to lowercase

    text = text.lower()


    # Remove URLs

    text = re.sub(
        r'http\S+|www\S+|https\S+',
        '',
        text
    )


    # Remove special characters and numbers

    text = re.sub(
        r'[^a-zA-Z\s]',
        '',
        text
    )


    # Split text into words

    words = text.split()


    # Remove stopwords

    words = [
        word
        for word in words
        if word not in stop_words
    ]


    # Apply stemming

    words = [
        stemmer.stem(word)
        for word in words
    ]


    # Join words

    return ' '.join(words)


# Apply preprocessing

df['clean_message'] = (
    df['message']
    .apply(preprocess_text)
)


print("\nOriginal and preprocessed messages:")

print(
    df[
        ['message', 'clean_message']
    ].head()
)

"""9. ENCODE TARGET VARIABLE"""

# ham = 0
# spam = 1

df['label_encoded'] = df['label'].map({
    'ham': 0,
    'spam': 1
})


print(df[
    ['label', 'label_encoded']
].head())

"""10. DEFINE INPUT AND TARGET"""

X = df['clean_message']

y = df['label_encoded']


print("\nInput variable X:")
print(X.head())


print("\nTarget variable y:")
print(y.head())

"""11. TRAIN-TEST SPLIT"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)


print("Training samples:", len(X_train))

print("Testing samples:", len(X_test))

"""12. TF-IDF VECTORIZATION"""

# Create TF-IDF vectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2)
)


# Fit and transform training data

X_train_tfidf = tfidf.fit_transform(
    X_train
)


# Transform testing data

X_test_tfidf = tfidf.transform(
    X_test
)


print("TF-IDF training shape:",
      X_train_tfidf.shape)

print("TF-IDF testing shape:",
      X_test_tfidf.shape)

"""13. TRAIN NAIVE BAYES MODEL"""

# Create Multinomial Naive Bayes model

model = MultinomialNB()


# Train the model

model.fit(
    X_train_tfidf,
    y_train
)


print("Naive Bayes model trained successfully!")

""" 14. MAKE PREDICTIONS"""

y_pred = model.predict(
    X_test_tfidf
)


print("Predictions generated successfully!")

"""15. MODEL EVALUATION"""

# Accuracy

accuracy = accuracy_score(
    y_test,
    y_pred
)


# Precision

precision = precision_score(
    y_test,
    y_pred
)


# Recall

recall = recall_score(
    y_test,
    y_pred
)


# F1-score

f1 = f1_score(
    y_test,
    y_pred
)


print("\nAccuracy :",
      round(accuracy * 100, 2), "%")


print("Precision:",
      round(precision * 100, 2), "%")


print("Recall   :",
      round(recall * 100, 2), "%")


print("F1-Score :",
      round(f1 * 100, 2), "%")

"""16. CLASSIFICATION REPORT"""

print(
    classification_report(
        y_test,
        y_pred,
        target_names=[
            'Ham',
            'Spam'
        ]
    )
)

"""17. CONFUSION MATRIX"""

cm = confusion_matrix(
    y_test,
    y_pred
)


print(cm)


# Plot confusion matrix

plt.figure(
    figsize=(7, 5)
)


sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=[
        'Ham',
        'Spam'
    ],
    yticklabels=[
        'Ham',
        'Spam'
    ]
)


plt.title(
    "Confusion Matrix - SMS Spam Detection"
)

plt.xlabel(
    "Predicted Label"
)

plt.ylabel(
    "Actual Label"
)

plt.show()

"""18. PERFORMANCE METRICS GRAPH"""

from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score)

# Assuming y_test and y_pred are available from previous cells.
# Accuracy
accuracy = accuracy_score(
    y_test,
    y_pred
)


# Precision
precision = precision_score(
    y_test,
    y_pred
)


# Recall
recall = recall_score(
    y_test,
    y_pred
)


# F1-score
f1 = f1_score(
    y_test,
    y_pred
)


metrics = [
    'Accuracy',
    'Precision',
    'Recall',
    'F1-Score'
]


values = [
    accuracy,
    precision,
    recall,
    f1
]


plt.figure(
    figsize=(8, 5)
)


plt.bar(
    metrics,
    values
)


plt.ylim(
    0,
    1
)


plt.title(
    "Model Performance Metrics"
)


plt.xlabel(
    "Evaluation Metric"
)


plt.ylabel(
    "Score"
)


plt.show()

"""19. CUSTOM SMS PREDICTION"""

def predict_sms(message):
    """
    Predict whether a new SMS is spam or ham.
    """

    # Preprocess new message

    cleaned_message = preprocess_text(
        message
    )


    # Convert message into TF-IDF

    message_tfidf = tfidf.transform(
        [cleaned_message]
    )


    # Make prediction

    prediction = model.predict(
        message_tfidf
    )[0]


    # Get probability

    probability = model.predict_proba(
        message_tfidf
    )[0]


    if prediction == 1:

        result = "SPAM"

    else:

        result = "HAM"


    return result, probability

"""20. TEST SAMPLE MESSAGES"""

sample_messages = [

    "Congratulations! You have won a free prize. Call now!",

    "Hey, are you coming to college tomorrow?",

    "You have been selected for a cash reward. Claim now!",

    "Can you send me the assignment?"
]


for message in sample_messages:

    result, probability = predict_sms(
        message
    )

    print("\nMessage:", message)

    print("Prediction:", result)

"""21. INTERACTIVE APPLICATION"""

print(
    "\nEnter an SMS message to classify."
)

print(
    "Type 'exit' to stop the application."
)


while True:

    user_message = input(
        "\nEnter SMS: "
    )


    if user_message.lower() == 'exit':

        print(
            "SMS Spam Detector stopped."
        )

        break

    result, probability = predict_sms(
        user_message
    )


    print(
        "Prediction:",
        result
    )

""" Conclusion

The SMS Spam Detection system was successfully developed using NLP and machine learning techniques. The model achieved 96.71% accuracy, 98.99% precision, 74.81% recall and 85.22% F1-score.

The project demonstrates that NLP techniques such as text preprocessing and TF-IDF, combined with Multinomial Naive Bayes, can effectively classify SMS messages as Ham or Spam.
"""
